import React, { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Moon, 
  Quote, 
  Smile, 
  Zap, 
  BookOpen, 
  Menu, 
  RotateCcw, 
  BarChart2, 
  Printer, 
  Clock, 
  Brain, 
  X, 
  Eye, 
  Download, 
  Search,
  Star,
  ArrowLeft,
  Trash2,
  Filter,
  Loader2,
  Share2,
  FileText,
  Info,
  Sparkles
} from 'lucide-react';
import { useSyllabusStore } from '../../store';
import { geminiService } from '../../services/geminiService';
import { ZineGenerator } from '../shared/ZineGenerator';
import { ReadAloudButton } from '../shared/ReadAloudButton';
import { ResultSection } from '../shared/ResultSection';
import { ToolLayout } from '../shared/ToolLayout';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { LexiconText } from '../shared/LexiconText';

interface MasterArchiveProps {
  onBack: () => void;
}

type TimelineItem = {
  id: string;
  type: 'DREAM' | 'QUOTE' | 'MOOD' | 'READING' | 'SYNCHRONICITY' | 'AKASHIC' | 'BIRTH_CHART' | 'DEATH_CLOCK' | 'SONG_ORACLE' | 'TEA_LEAF' | 'NUMEROLOGY' | 'DAILY_RITUAL' | 'PENDULUM' | 'COLOR_ORACLE' | 'LOST_ITEM' | 'SCRYING' | 'BIORHYTHM' | 'GEMATRIA' | 'HUMAN_DESIGN' | 'SABIAN' | 'LENORMAND';
  title: string;
  content: string;
  date: string;
  timestamp: number;
  icon: any;
  color: string;
  metadata?: any;
};

export const MasterArchive: React.FC<MasterArchiveProps> = ({ onBack }) => {
  const { 
    dreams, quotes, moodLogs, horaryHistory, synchronicityHistory, akashicHistory, tarotHistory, lenormandHistory,
    sigils, teaLeafReadings, starboard,
    removeDream, removeQuote, removeMoodLog, removeHoraryEntry, removeSynchronicityEntry, removeAkashicEntry, removeTarotEntry, removeLenormandEntry,
    removeSigil, removeTeaLeafReading, removeStar,
    resetAllData
  } = useSyllabusStore();

  const [selectedItem, setSelectedItem] = useState<TimelineItem | null>(null);
  const [showZine, setShowZine] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState<TimelineItem['type'] | 'ALL'>('ALL');
  const [isSynthesizing, setIsSynthesizing] = useState(false);
  const [synthesis, setSynthesis] = useState<string | null>(null);
  const [showStats, setShowStats] = useState(false);
  const [isConfirmingClear, setIsConfirmingClear] = useState(false);

  const timeline = useMemo(() => {
    let items: TimelineItem[] = [];

    // Add Starboard entries (Aggregated from all tools)
    starboard.forEach(s => {
      // Avoid duplicates if the same item is in both a specific history and starboard
      // (Though starboard entries usually have unique IDs generated by ResultSection)
      items.push({
        id: s.id,
        type: (s.type as any) || 'READING', 
        title: s.title,
        content: s.content,
        date: new Date(s.date).toLocaleDateString(),
        timestamp: new Date(s.date).getTime(),
        icon: () => <Star className="w-4 h-4" />,
        color: 'text-archive-accent',
        metadata: s.metadata
      });
    });

    dreams.forEach(d => {
      items.push({
        id: d.id,
        type: 'DREAM',
        title: 'Nocturnal Vision',
        content: d.text,
        date: d.date,
        timestamp: new Date(d.date).getTime(),
        icon: () => <Moon className="w-4 h-4" />,
        color: 'text-archive-accent-secondary'
      });
    });

    quotes.forEach(q => {
      if (q.author === 'You') {
        items.push({
          id: q.id,
          type: 'QUOTE',
          title: 'Personal Wisdom',
          content: q.text,
          date: 'Archived',
          timestamp: 0,
          icon: () => <Quote className="w-4 h-4" />,
          color: 'text-archive-accent'
        });
      }
    });

    moodLogs.forEach(m => {
      items.push({
        id: m.id,
        type: 'MOOD',
        title: `Resonance: ${m.mood}`,
        content: m.insight,
        date: new Date(m.date).toLocaleDateString(),
        timestamp: new Date(m.date).getTime(),
        icon: () => <Smile className="w-4 h-4" />,
        color: 'text-archive-accent-tertiary'
      });
    });

    horaryHistory.forEach(h => {
      items.push({
        id: h.id,
        type: 'READING',
        title: 'Celestial Inquiry',
        content: h.question,
        date: new Date(h.date).toLocaleDateString(),
        timestamp: new Date(h.date).getTime(),
        icon: () => <Star className="w-4 h-4" />,
        color: 'text-archive-accent-quaternary',
        metadata: {
          outcome: h.outcome,
          judgment: h.judgment,
          location: h.location
        }
      });
    });

    synchronicityHistory.forEach(s => {
      items.push({
        id: s.id,
        type: 'SYNCHRONICITY',
        title: 'Synchronicity Decoded',
        content: s.event,
        date: new Date(s.date).toLocaleDateString(),
        timestamp: new Date(s.date).getTime(),
        icon: () => <Zap className="w-4 h-4" />,
        color: 'text-archive-accent-secondary',
        metadata: {
          interpretation: s.interpretation
        }
      });
    });

    akashicHistory.forEach(a => {
      items.push({
        id: a.id,
        type: 'AKASHIC',
        title: 'Akashic Record',
        content: a.query,
        date: new Date(a.date).toLocaleDateString(),
        timestamp: new Date(a.date).getTime(),
        icon: () => <BookOpen className="w-4 h-4" />,
        color: 'text-archive-accent',
        metadata: {
          insight: a.insight
        }
      });
    });

    tarotHistory.forEach(t => {
      items.push({
        id: t.id,
        type: 'READING',
        title: `Tarot: ${t.spread.replace('-', ' ')}`,
        content: t.question,
        date: new Date(t.date).toLocaleDateString(),
        timestamp: new Date(t.date).getTime(),
        icon: () => <Menu className="w-4 h-4" />,
        color: 'text-archive-accent-secondary',
        metadata: {
          synthesis: t.synthesis,
          cards: t.cards
        }
      });
    });

    lenormandHistory.forEach(l => {
      const isStructured = typeof l.interpretation !== 'string';
      items.push({
        id: l.id,
        type: 'READING',
        title: 'Lenormand Spin',
        content: l.cards.join(' + '),
        date: new Date(l.date).toLocaleDateString(),
        timestamp: new Date(l.date).getTime(),
        icon: () => <RotateCcw className="w-4 h-4" />,
        color: 'text-archive-accent-tertiary',
        metadata: {
          practical: isStructured ? (l.interpretation as any).practical : l.interpretation,
          psychological: isStructured ? (l.interpretation as any).psychological : '',
          spiritual: isStructured ? (l.interpretation as any).spiritual : '',
          cards: l.cards
        }
      });
    });

    sigils.forEach(s => {
      items.push({
        id: s.id,
        type: 'SYNCHRONICITY',
        title: 'Sigil Manifestation',
        content: s.intent,
        date: new Date(s.date).toLocaleDateString(),
        timestamp: new Date(s.date).getTime(),
        icon: () => <Zap className="w-4 h-4" />,
        color: 'text-archive-accent-secondary',
        metadata: {
          interpretation: s.interpretation,
          path: s.path
        }
      });
    });

    teaLeafReadings.forEach(t => {
      items.push({
        id: t.id,
        type: 'READING',
        title: 'Tea Leaf Reading',
        content: t.vision,
        date: new Date(t.date).toLocaleDateString(),
        timestamp: new Date(t.date).getTime(),
        icon: () => <Moon className="w-4 h-4" />,
        color: 'text-archive-accent-tertiary',
        metadata: {
          interpretation: t.interpretation
        }
      });
    });

    // Apply Filters
    if (filterType !== 'ALL') {
      items = items.filter(i => i.type === filterType);
    }

    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      items = items.filter(i => 
        i.title.toLowerCase().includes(q) || 
        i.content.toLowerCase().includes(q) ||
        (i.metadata?.outcome?.toLowerCase().includes(q)) ||
        (i.metadata?.judgment?.toLowerCase().includes(q)) ||
        (i.metadata?.interpretation?.toLowerCase().includes(q)) ||
        (i.metadata?.insight?.toLowerCase().includes(q)) ||
        (i.metadata?.synthesis?.toLowerCase().includes(q)) ||
        (i.metadata?.practical?.toLowerCase().includes(q)) ||
        (i.metadata?.psychological?.toLowerCase().includes(q)) ||
        (i.metadata?.spiritual?.toLowerCase().includes(q))
      );
    }

    return items.sort((a, b) => b.timestamp - a.timestamp);
  }, [dreams, quotes, moodLogs, horaryHistory, synchronicityHistory, akashicHistory, tarotHistory, lenormandHistory, sigils, teaLeafReadings, filterType, searchQuery]);

  const handleDelete = (item: TimelineItem) => {
    // Always try to remove from starboard as well
    removeStar(item.id);

    switch (item.type) {
      case 'DREAM': removeDream(item.id); break;
      case 'QUOTE': removeQuote(item.id); break;
      case 'MOOD': removeMoodLog(item.id); break;
      case 'READING': 
      case 'TEA_LEAF':
      case 'LENORMAND':
        removeHoraryEntry(item.id); 
        removeTarotEntry(item.id);
        removeLenormandEntry(item.id);
        removeTeaLeafReading(item.id);
        break;
      case 'SYNCHRONICITY': 
        removeSynchronicityEntry(item.id); 
        removeSigil(item.id);
        break;
      case 'AKASHIC': removeAkashicEntry(item.id); break;
      default:
        // For other types like BIRTH_CHART, DEATH_CLOCK, etc.
        // they are primarily managed via starboard which is already handled by removeStar above.
        break;
    }
  };

  const handleExport = (item: TimelineItem) => {
    let text = `[${item.type}] ${item.title}\nDate: ${item.date}\nContent: ${item.content}`;
    
    if (item.metadata) {
      if (item.metadata.outcome) text += `\nOutcome: ${item.metadata.outcome}`;
      if (item.metadata.judgment) text += `\nJudgment: ${item.metadata.judgment}`;
      if (item.metadata.synthesis) text += `\nSynthesis: ${item.metadata.synthesis}`;
      if (item.metadata.practical) text += `\nPractical: ${item.metadata.practical}`;
      if (item.metadata.psychological) text += `\nPsychological: ${item.metadata.psychological}`;
      if (item.metadata.spiritual) text += `\nSpiritual: ${item.metadata.spiritual}`;
      if (item.metadata.cards) {
        text += `\nCards: ${item.metadata.cards.map((c: any) => `${c.name} (${c.isReversed ? 'Reversed' : 'Upright'}) at ${c.position}`).join(', ')}`;
      }
    }
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `syllabus-record-${item.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSynthesize = async () => {
    if (timeline.length < 3) {
      console.error("Insufficient data for synthesis.");
      return;
    }
    
    setIsSynthesizing(true);
    setSynthesis(null);
    
    try {
      const records = timeline.slice(0, 15).map(i => `[${i.type}] ${i.title}: ${i.content}`).join('\n');
      
      const prompt = `You are the Master Librarian of the Archive. 
      Analyze the following recent records from a seeker's syllabus and provide a "Deep Resonance Synthesis".
      Identify recurring themes, hidden patterns, and a singular "Core Frequency" for this period.
      
      Records:
      ${records}
      
      Format the response as a poetic but structured report in the 'Archive/Syllabus' aesthetic. 
      Include:
      1. THEMES: 2-3 recurring concepts.
      2. PATTERNS: Observations on how the seeker's mood, dreams, and inquiries correlate.
      3. CORE FREQUENCY: A singular evocative phrase representing the current state.
      
      Keep it under 200 words. Use serif-style language.`;

      const text = await geminiService.generateText(prompt);
      setSynthesis(text);
    } catch (error) {
      console.error("Synthesis error:", error);
      setSynthesis("The records are currently clouded. Return when the celestial alignment is clearer.");
    } finally {
      setIsSynthesizing(false);
    }
  };

  const statsData = useMemo(() => {
    const counts = timeline.reduce((acc, item) => {
      acc[item.type] = (acc[item.type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return Object.entries(counts).map(([name, value]) => ({ name, value }));
  }, [timeline]);

  return (
    <div className="flex-1 flex flex-col overflow-hidden bg-archive-bg">
      <header className="border-b border-archive-line p-6 flex items-center justify-between bg-archive-bg">
        <div className="flex items-center gap-8">
          <button onClick={onBack} className="text-xs font-mono opacity-40 hover:opacity-100 transition-opacity flex items-center gap-2">
            <ArrowLeft className="w-3 h-3" /> BACK
          </button>
          <h1 className="font-serif italic text-2xl tracking-tight">The Master Syllabus</h1>
        </div>
        <div className="flex items-center gap-6">
          {isConfirmingClear ? (
            <div className="flex items-center gap-3">
              <span className="text-[10px] font-mono uppercase text-red-500 animate-pulse">Confirm Clear?</span>
              <button 
                onClick={() => {
                  resetAllData();
                  setIsConfirmingClear(false);
                }}
                className="text-[10px] font-mono uppercase tracking-widest px-2 py-1 bg-red-500 text-white rounded hover:bg-red-600 transition-colors"
              >
                Yes
              </button>
              <button 
                onClick={() => setIsConfirmingClear(false)}
                className="text-[10px] font-mono uppercase tracking-widest px-2 py-1 bg-archive-ink/10 text-archive-ink/60 rounded hover:bg-archive-ink/20 transition-colors"
              >
                No
              </button>
            </div>
          ) : (
            <button 
              onClick={() => setIsConfirmingClear(true)}
              className="text-[10px] font-mono uppercase tracking-widest flex items-center gap-2 text-red-500/60 hover:text-red-500 transition-colors"
            >
              Delete Clear Archive
            </button>
          )}
          <button 
            onClick={() => setShowStats(!showStats)}
            className={`text-[10px] font-mono uppercase tracking-widest flex items-center gap-2 transition-colors ${showStats ? 'text-archive-accent' : 'hover:text-archive-accent'}`}
          >
            <BarChart2 className="w-3 h-3" /> {showStats ? 'Hide Stats' : 'Resonance Graph'}
          </button>
          <button 
            onClick={() => setShowZine(true)}
            className="text-[10px] font-mono uppercase tracking-widest flex items-center gap-2 hover:text-archive-accent transition-colors"
          >
            <Printer className="w-3 h-3" /> Print Monthly Zine
          </button>
          <div className="flex items-center gap-4 text-[10px] uppercase tracking-syllabus opacity-40">
            <Clock className="w-3 h-3" /> Timeline View
          </div>
        </div>
      </header>

      <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
        <div className="max-w-4xl mx-auto space-y-12">
          <div className="text-center space-y-4">
            <h2 className="title-main text-6xl">Chronological Resonance</h2>
            <p className="opacity-60">Every echo, every vision, every insight recorded in the Syllabus.</p>
            
            <div className="pt-6">
              <button 
                onClick={handleSynthesize}
                disabled={isSynthesizing}
                className="brutalist-button px-8 py-3 text-sm flex items-center gap-3 mx-auto group"
              >
                {isSynthesizing ? <div className="animate-spin w-4 h-4 border-2 border-current border-t-transparent rounded-full" /> : <Brain className="w-4 h-4 group-hover:scale-110 transition-transform" />}
                {isSynthesizing ? 'SYNTHESIZING...' : 'GENERATE SYLLABUS SYNTHESIS'}
              </button>
            </div>
          </div>

          <AnimatePresence>
            {synthesis && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="overflow-hidden"
              >
                <div className="p-10 border border-archive-accent/30 bg-archive-accent/[0.02] relative">
                  <button 
                    onClick={() => setSynthesis(null)}
                    className="absolute top-4 right-4 opacity-20 hover:opacity-100"
                  >
                    <X className="w-4 h-4" />
                  </button>
                  <div className="flex items-center gap-3 mb-6">
                    <Brain className="text-archive-accent w-5 h-5" />
                    <span className="text-[10px] font-mono uppercase tracking-[0.3em] text-archive-accent font-bold">Deep Resonance Synthesis</span>
                    <div className="flex-1" />
                    <ReadAloudButton text={synthesis} className="!p-1 !h-auto !w-auto !bg-transparent !border-none !shadow-none opacity-20 hover:opacity-100" />
                  </div>
                  <div className="prose prose-sm max-w-none font-serif italic text-lg leading-relaxed text-archive-ink whitespace-pre-wrap">
                    {synthesis}
                  </div>
                </div>
              </motion.div>
            )}

            {showStats && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="overflow-hidden"
              >
                <div className="p-8 border border-archive-line bg-archive-bg shadow-sm h-64">
                  <div className="flex items-center gap-3 mb-6">
                    <BarChart2 className="opacity-40 w-5 h-5 text-archive-ink" />
                    <span className="text-[10px] font-mono uppercase tracking-[0.3em] opacity-40 text-archive-ink">Entry Frequency by Type</span>
                  </div>
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={statsData}>
                      <XAxis 
                        dataKey="name" 
                        axisLine={false} 
                        tickLine={false} 
                        tick={{ fontSize: 9, fontFamily: 'monospace', fill: 'var(--color-archive-ink)', opacity: 0.4 }}
                      />
                      <YAxis hide />
                      <Tooltip 
                        cursor={{ fill: 'var(--color-archive-line)', opacity: 0.1 }}
                        contentStyle={{ backgroundColor: 'var(--color-archive-bg)', border: '1px solid var(--color-archive-line)', fontSize: '10px', fontFamily: 'monospace', color: 'var(--color-archive-ink)' }}
                      />
                      <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                        {statsData.map((entry, index) => (
                          <Cell 
                            key={`cell-${index}`} 
                            fill={
                              entry.name === 'DREAM' ? 'var(--color-archive-accent-secondary)' : 
                              entry.name === 'READING' ? 'var(--color-archive-accent-quaternary)' :
                              entry.name === 'MOOD' ? 'var(--color-archive-accent-tertiary)' :
                              entry.name === 'SYNCHRONICITY' ? 'var(--color-archive-accent-secondary)' : 
                              entry.name === 'QUOTE' ? 'var(--color-archive-accent)' : '#000'
                            } 
                          />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          <div className="space-y-6">
            <div className="flex flex-col md:flex-row gap-4 items-center justify-between">
              <div className="relative w-full md:w-96">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 opacity-30 w-4 h-4 text-archive-ink" />
                <input 
                  type="text" 
                  placeholder="Search the archive..." 
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full bg-archive-bg border border-archive-line p-3 pl-10 text-sm font-serif italic outline-none focus:border-archive-accent shadow-sm text-archive-ink"
                />
              </div>
              <div className="flex flex-wrap gap-2 justify-center">
                {(['ALL', 'DREAM', 'READING', 'SYNCHRONICITY', 'AKASHIC', 'MOOD'] as const).map((type) => (
                  <button
                    key={type}
                    onClick={() => setFilterType(type)}
                    className={`px-3 py-1 text-[9px] font-mono uppercase tracking-widest border transition-all ${filterType === type ? 'bg-archive-ink text-archive-bg border-archive-ink' : 'border-archive-line opacity-40 hover:opacity-100'}`}
                  >
                    {type}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {timeline.map((item, idx) => (
              <motion.div 
                key={item.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                className="relative"
              >
                <div className="bg-archive-bg border border-archive-line p-8 shadow-sm hover:shadow-md transition-shadow group h-full flex flex-col">
                  <div className="flex justify-between items-start mb-4">
                    <div className="flex items-center gap-3 text-archive-ink">
                      <item.icon />
                      <span className="text-[10px] font-mono uppercase tracking-[0.2em]">{item.title}</span>
                    </div>
                    <span className="text-[10px] font-mono opacity-40 uppercase tracking-widest text-archive-ink">{item.date}</span>
                  </div>
                  
                  <p className="font-serif italic text-xl leading-relaxed text-archive-ink line-clamp-3">
                    {item.content}
                  </p>

                  <div className="mt-6 pt-4 border-t border-archive-line flex justify-between items-center opacity-0 group-hover:opacity-100 transition-opacity">
                    <span className="text-[9px] font-mono uppercase opacity-40">ID: {item.id.slice(0, 8)}</span>
                    <div className="flex gap-4">
                       <button 
                        onClick={() => setSelectedItem(item)}
                        className="text-[9px] font-mono uppercase flex items-center gap-1 hover:text-archive-accent transition-colors"
                       >
                         <Eye className="w-3 h-3" /> Details
                       </button>
                       <button 
                        onClick={() => handleExport(item)}
                        className="text-[9px] font-mono uppercase flex items-center gap-1 hover:text-archive-accent transition-colors"
                       >
                         <Download className="w-3 h-3" /> Export
                       </button>
                       <button 
                        onClick={() => handleDelete(item)}
                        className="text-[9px] font-mono uppercase flex items-center gap-1 hover:text-red-500 transition-colors"
                       >
                         Delete
                       </button>
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}

            {timeline.length === 0 && (
              <div className="text-center py-24 border border-dashed border-archive-line rounded-3xl opacity-20 italic font-serif text-2xl">
                The syllabus is currently empty. Begin your journey to record your first resonance.
              </div>
            )}
          </div>
        </div>
      </div>

      <AnimatePresence>
        {selectedItem && (
          <div className="fixed inset-0 z-[3000] flex items-center justify-center p-6">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedItem(null)}
              className="absolute inset-0 bg-archive-bg/80 backdrop-blur-sm"
            />
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-2xl bg-archive-bg border border-archive-line p-10 shadow-2xl overflow-y-auto max-h-[80vh] custom-scrollbar"
            >
              <ResultSection
                id={selectedItem.id}
                type={selectedItem.type}
                title={selectedItem.title}
                content={selectedItem.content}
                exportName={`archive-${selectedItem.type.toLowerCase()}-${selectedItem.id}`}
                metadata={selectedItem.metadata}
              >
                <button 
                  onClick={() => setSelectedItem(null)}
                  className="absolute top-6 right-6 text-archive-ink opacity-40 hover:opacity-100 transition-opacity z-20"
                >
                  <X className="w-4 h-4" />
                </button>

                <div className="space-y-8">
                  <div className="flex items-center gap-4 border-b border-archive-line pb-6">
                    <selectedItem.icon />
                    <div>
                      <h3 className="text-[10px] font-mono uppercase tracking-widest opacity-40">{selectedItem.type} RECORD</h3>
                      <div className="flex items-center gap-4">
                        <h2 className="text-3xl font-serif italic">{selectedItem.title}</h2>
                        <ReadAloudButton text={`${selectedItem.content} ${selectedItem.metadata?.judgment || ''} ${selectedItem.metadata?.interpretation || ''} ${selectedItem.metadata?.insight || ''}`} className="!p-1 !h-auto !w-auto !bg-transparent !border-none !shadow-none opacity-20 hover:opacity-100" />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-6">
                    <div className="space-y-2">
                      <label className="text-[9px] font-mono uppercase opacity-40">Syllabus Content</label>
                      <div className="font-serif italic text-2xl leading-relaxed text-archive-ink markdown-body">
                        <LexiconText>{selectedItem.content}</LexiconText>
                      </div>
                    </div>

                    {selectedItem.metadata && (
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-6 border-t border-archive-line">
                        {selectedItem.metadata.outcome && (
                          <div className="space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Outcome</label>
                            <p className="handwritten text-lg text-archive-accent-quaternary">{selectedItem.metadata.outcome}</p>
                          </div>
                        )}
                        {selectedItem.metadata.location && (
                          <div className="space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Location</label>
                            <p className="handwritten text-lg">{selectedItem.metadata.location}</p>
                          </div>
                        )}
                        {selectedItem.metadata.judgment && (
                          <div className="col-span-full space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Judgment</label>
                            <p className="handwritten text-lg italic leading-relaxed">{selectedItem.metadata.judgment}</p>
                          </div>
                        )}
                        {selectedItem.metadata.interpretation && (
                          <div className="col-span-full space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Esoteric Interpretation</label>
                            <p className="handwritten text-lg italic leading-relaxed text-archive-accent-secondary">{selectedItem.metadata.interpretation}</p>
                          </div>
                        )}
                        {selectedItem.metadata.insight && (
                          <div className="col-span-full space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Akashic Insight</label>
                            <p className="handwritten text-lg italic leading-relaxed text-archive-accent">{selectedItem.metadata.insight}</p>
                          </div>
                        )}
                        {selectedItem.metadata.physical !== undefined && (
                          <div className="space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Physical Cycle</label>
                            <p className="handwritten text-lg">{Math.round(selectedItem.metadata.physical * 100)}%</p>
                          </div>
                        )}
                        {selectedItem.metadata.emotional !== undefined && (
                          <div className="space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Emotional Cycle</label>
                            <p className="handwritten text-lg">{Math.round(selectedItem.metadata.emotional * 100)}%</p>
                          </div>
                        )}
                        {selectedItem.metadata.intellectual !== undefined && (
                          <div className="space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Intellectual Cycle</label>
                            <p className="handwritten text-lg">{Math.round(selectedItem.metadata.intellectual * 100)}%</p>
                          </div>
                        )}
                        {selectedItem.metadata.answer && (
                          <div className="col-span-full space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Pendulum Answer</label>
                            <p className="handwritten text-lg italic">{selectedItem.metadata.answer}</p>
                          </div>
                        )}
                        {selectedItem.metadata.vision && (
                          <div className="col-span-full space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Scrying Vision</label>
                            <p className="handwritten text-lg italic">{selectedItem.metadata.vision}</p>
                          </div>
                        )}
                        {selectedItem.metadata.story && (
                          <div className="col-span-full space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Cosmic Story</label>
                            <p className="handwritten text-lg italic leading-relaxed">{selectedItem.metadata.story}</p>
                          </div>
                        )}
                        {selectedItem.metadata.ritual && (
                          <div className="col-span-full space-y-1">
                            <label className="text-[9px] font-mono uppercase opacity-40">Daily Ritual</label>
                            <p className="handwritten text-lg italic">{selectedItem.metadata.ritual}</p>
                          </div>
                        )}
                      </div>
                    )}

                    <div className="pt-8 flex justify-between items-center text-[10px] font-mono uppercase opacity-40">
                      <div className="flex flex-col gap-1">
                        <span>Recorded on {selectedItem.date}</span>
                        <span>System ID: {selectedItem.id}</span>
                      </div>
                      <button 
                        onClick={() => handleDelete(selectedItem)}
                        className="text-red-500/60 hover:text-red-500 flex items-center gap-2 transition-colors"
                      >
                        <Trash2 className="w-3 h-3" /> Purge
                      </button>
                    </div>
                  </div>
                </div>
              </ResultSection>
            </motion.div>
          </div>
        )}

        {showZine && (
          <ZineGenerator onClose={() => setShowZine(false)} />
        )}
      </AnimatePresence>
    </div>
  );
};
